### ISSUE TITLE
Exporting hacks

### ISSUE THREAD

**Issue by husseinalhammad** [dylanatsmith/howtotarget#32]
One of the things the [Email Markup Consortium](https://github.com/email-markup-consortium) does is analyses HTML emails to continuously report on the state of HTML emails, among other things. One idea that was brought up during discussions (expectedly by @M-J-Robbins) is to check for email targeting hacks in our analysis. 

The hacks are already open source (thanks!). I'm sure we can programmatically grab all code blocks from the markdown files in [hacks/_posts](https://github.com/dylanatsmith/howtotarget/tree/main/hacks/_posts). 

Not sure if it is reasonable to expect this project to provide the hacks in a different format though. Potentially out of scope. If not, does this format (from [maizzle/email-normalize](https://github.com/maizzle/email-normalize)) make sense in this context? https://github.com/maizzle/email-normalize/blob/main/src/index.js

**Comment by dylanatsmith** [comment]
In theory we could add a file in any format to the build of this project so that whenever anything is added or changed it gets updated.

You’d still need to write some extra processing bits on the other side to use wildcards instead of `foo` or comments, for example.

Since this would basically be a custom API for Email Markup Consortium, can we get an example of the optimal desired formatting?

Data we currently have:
* Top level posts are called "hacks"
* Date created (currently an ISO-8601 string but might be able to get a Unix timestamp from Jekyll)
* Client (string)
* Version (integer)
* Platform (string)
  * Sometimes combined, like `iOS & Android` or `Phone & Surface`
* Status (string)
  * One of `Working`, `Deprecated`, or `Unknown`
* Contributor (string)
* Body
  * Includes both the fenced code block and any description
  * Description can include inline code
  * In theory could include multiple fenced code blocks and other elements like richer samples/tests in the future (https://github.com/dylanatsmith/howtotarget/issues/27)

**Comment by dylanatsmith** [comment]
As an example of the implementation that comes to mind, see the custom RSS feed that uses Liquid:

https://github.com/dylanatsmith/howtotarget/blob/main/feed.xml

No reason we couldn’t generate e.g. howtotarget.email/hacks.json with a loop the same way.

**Comment by husseinalhammad** [comment]
This sounds like a reasonable approach 👍

> Since this would basically be a custom API for Email Markup Consortium, can we get an example of the optimal desired formatting?

I'll need to check with the individuals that intend to utilise this data. I (or they) will get back to you on this.

> You’d still need to write some extra processing bits on the other side to use wildcards instead of `foo` or comments, for example.

Noted. For CSS selectors, assuming all hacks follow the same naming convention, this should not be a huge pain to deal with. e.g. `.body` always refers to `<body class="body">`.

**Comment by dylanatsmith** [comment]
@husseinalhammad Is this still something you’re interested in?

**Comment by avigoldman** [comment]
I'd be very interested in a JSON version of the feed :)

**Comment by dylanatsmith** [comment]
Dropping this here for myself to reference.

https://jsonapi.org/

**Comment by husseinalhammad** [comment]
> Data we currently have

I realise code fences have the language on there so it would be easy to grab, but some hacks may have `html` as the language, but still rely on some CSS to work like this one:

https://github.com/dylanatsmith/howtotarget/blob/main/hacks/_posts/2021-10-08-yahoo-japan.md

Not sure how useful it would be to include what the hack uses in the feed:

```json
{
  "uses": [
    "css"
  ]
}
```

```json
{
  "uses": [
    "css",
    "html"
  ]
}
```

**Comment by dylanatsmith** [comment]
> Not sure how useful it would be to include what the hack uses in the feed

If this would be useful, it can be added. The best way is probably just opening a PR to update the front matter of each post and then following the new format moving forward.

Something like:

```markdown
---
client: Android
platform:
version:
status: Working
languages:
  - HTML
  - CSS
contributor: Mark Robbins
---
```
